name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Raven
        uses: martian56/setup-raven@v1

      - name: Build
        run: rvpm build

      - name: Test
        run: rvpm test

      - name: Format check
        run: rvpm fmt --check
